module.exports = [
  require('./palettes/bw.js'),
  require('./palettes/dmg.js'),
  require('./palettes/gbpocket.js'),
  require('./palettes/gbcjp.js'),
  require('./palettes/gbcua.js'),
  require('./palettes/gbcub.js'),
  require('./palettes/gbcl.js'),
  require('./palettes/gbcla.js'),
  require('./palettes/gbclb.js'),
  require('./palettes/gbcd.js'),
  require('./palettes/gbcda.js'),
  require('./palettes/gbcdb.js'),
  require('./palettes/gbcr.js'),
  require('./palettes/gbceuus.js'),
  require('./palettes/gbcrb.js'),
];
